name: Build LaTeX

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  latex-build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: apt-get update && apt-get install -y jq

      - name: Build .tex files
        run: |
          command=$(jq -r \
            --arg tools "latex-workshop.latex.tools" \
            --arg command "command" \
            --arg args "args" \
            '.[$tools][] | [.[$command]] + .[$args] | join(" ")' \
            .vscode/settings.json)
          for tex_file in *.tex; do
            tex_command="$(echo "$command" | sed "s/%DOC%/$tex_file/g" | sed "s/%DIR%/./g")"
            eval "$tex_command"
          done

      - name: Upload .tex files
        id: upload
        shell: bash
        run: |
          outdir=$(jq -r \
            --arg tools "latex-workshop.latex.tools" \
            --arg args "args" \
            '.[$tools][] | .[$args][] | select(startswith("-outdir=")) | split("=")[1]' \
            .vscode/settings.json | sed "s/%DIR%/./g")
          echo pdf_paths="$outdir/*.pdf" >> "$GITHUB_OUTPUT"
          echo artifact_name=${GITHUB_REPOSITORY#*/}-${GITHUB_SHA::7} >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.upload.outputs.artifact_name }}
          path: ${{ steps.upload.outputs.pdf_paths }}
