name: Build LaTeX

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  latex-build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: apt-get update && apt-get install -y jq

      - name: Build .tex files
        run: |
          command=$(jq -r \
            --arg tools "latex-workshop.latex.tools" \
            --arg command "command" \
            --arg args "args" \
            '.[$tools][] | [.[$command]] + .[$args] | join(" ")' \
            .vscode/settings.json)
          for tex_file in *.tex; do
            tex_command="$(echo "$command" | sed "s/%DOC%/$tex_file/g") -auxdir=action-aux -outdir=action-out"
            eval "$tex_command"
          done

      - name: Upload .tex files
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX Files
          path: |
            action-out/
